### ISSUE TITLE
Support wildcard lookup

### ISSUE THREAD

**Issue by jalaziz** [amplify-education/serverless-vpc-discovery#29]
When looking up subnet IDs, there is a step to "[Compare] the valid subnets with ones given to find invalid subnet names". This validation prevents using wildcards in the subnet names.

For example, instead of listing all subnets explicitly, I'd like to have a configuration that looks like:
```
vpc:
  vpcName: dev
  subnetNames:
    - 'dev-private-*'
```
