### ISSUE TITLE
Bug: wildcardMatches fails regex parsing for valid subnet tags

### ISSUE THREAD

**Issue by todd1uphealth** [amplify-education/serverless-vpc-discovery#59]
For subnets/etc that have tags with other regex key words (like parenthesis) in tag values affect parsing.

For example: 

```yml
custom:
  vpcDiscovery:
    vpcName: 'myVpc'
    subnets:
      - tagKey: Name
        tagValues:
          - 'MySubnet (Primary)'
```

will not match a vpc/subnet with the tag `Name='MySubnet (Primary)`
