### ISSUE TITLE
Error: Region is missing

### ISSUE THREAD

**Issue by jadsonbr** [amplify-education/serverless-vpc-discovery#84]
```yaml
...
custom:
  serverless-layers:
    dependenciesPath: requirements.txt
    packageManagerExtraArgs: '--no-compile --no-color'
  pythonRequirements:
    layer:
      name: ${env:function_name}-layer
  vpcDiscovery:
    vpcName: ${env:vpc_tag_name}-VPC
    subnets:
      - tagKey: Name
        tagValues:
          - '${env:vpc_tag_name}-Subnet-Private-A'
      - tagKey: Name
        tagValues:
          - '${env:vpc_tag_name}-Subnet-Private-B'
      - tagKey: Name
        tagValues:
          - '${env:vpc_tag_name}-Subnet-Private-C'
provider:
  region: us-east-1
...
```
To set up, as the example above worked until version 4.1.0, but after that version, it is presenting the error "**× Function 'lambda' VPC not configured based on the error: Error: Region is missing**." What do I need to change to make it work again?
